### ISSUE TITLE
where did the monarch biolink api go?

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/biolink-api#149]
https://api.monarchinitiative.org/
gives "Hello there"

**Comment by cmungall** [comment]
let's have this resolve to a basic page with some links, including a link to https://api.monarchinitiative.org/api/

**Comment by jmcmurry** [comment]
+1

**Comment by deepakunni3** [comment]
@cmungall Is this okay to merge?

**Comment by kshefchek** [comment]
https://api-dev.monarchinitiative.org/
