### ISSUE TITLE
Gene->Pathway->Gene error?

### ISSUE THREAD

**Issue by cbizon** [monarch-initiative/biolink-api#153]
I call /bioentity/gene/{id}/pathways/ with id = HGNC:5013
This gives me a list of pathway identifiers.

I can then call /bioentity/pathway/{id}/genes with each pathway identifier, and I think I should get HGNC:5013 as one of the returned genes.

But for REACT:R-HSA-168256, HGNC:5013 doesn't appear to be one of the genes returned.

Is this an error, or is the situation more complicated than I thought?

**Comment by kshefchek** [comment]
I think "immune system" is associated with a large number of proteins and genes: https://reactome.org/PathwayBrowser/#/R-HSA-168256&DTAB=MT

If you up the result count or page over the data HMOX1 should be there, for example:
https://api.monarchinitiative.org/api/bioentity/pathway/REACT%3AR-HSA-168256/genes/?rows=3000&fetch_objects=true

**Comment by cbizon** [comment]
Oh that makes sense. Thanks.
