### ISSUE TITLE
numFound returns null

### ISSUE THREAD

**Issue by putmantime** [monarch-initiative/biolink-api#155]
numFound has not been implemented for any calls that I can see.  This would be useful for web development especially.

{
"associations": [...],
"compact_associations": null,
"objects": [...],
"facet_counts": {...},
"numFound": null,
"start": null,
"facet_pivot": null
}

**Comment by deepakunni3** [comment]
It looks like this issue is coming from Ontobio, where we use PySolr to query and parse the response from Solr.

PySolr parses the response and interprets `numFound` as `hits`. While the `raw_response` still contains `numFound`, the actual property to access would be `results.hits`.
