### ISSUE TITLE
bioentityset/slimmer/function missing `reference` for GO annotations

### ISSUE THREAD

**Issue by nathandunn** [monarch-initiative/biolink-api#158]
bioentityset/slimmer/function 

Probably similar to the ontobio issue.  

The call I use is:

    https://api.monarchinitiative.org/api/bioentityset/slimmer/function?&slim=GO:0003824&slim=GO:0004872&slim=GO:0005102&slim=GO:0005215&slim=GO:0005198&slim=GO:0008092&slim=GO:0003677&slim=GO:0003723&slim=GO:0001071&slim=GO:0036094&slim=GO:0046872&slim=GO:0030246&slim=GO:0003674&slim=GO:0008283&slim=GO:0071840&slim=GO:0051179&slim=GO:0032502&slim=GO:0000003&slim=GO:0002376&slim=GO:0050877&slim=GO:0050896&slim=GO:0023052&slim=GO:0010467&slim=GO:0019538&slim=GO:0006259&slim=GO:0044281&slim=GO:0050789&slim=GO:0042592&slim=GO:0007610&slim=GO:0008150&slim=GO:0005576&slim=GO:0005737&slim=GO:0005856&slim=GO:0005739&slim=GO:0005634&slim=GO:0005694&slim=GO:0016020&slim=GO:0031982&slim=GO:0071944&slim=GO:0030054&slim=GO:0042995&slim=GO:0032991&slim=GO:0045202&slim=GO:0005575&subject=ZFIN:ZDB-GENE-990415-200

does not have the `reference` field:

    http://golr.geneontology.org/select?defType=edismax&qt=standard&indent=on&wt=json&rows=10&start=0&fl=*,score&facet=true&facet.mincount=1&facet.sort=count&json.nl=arrarr&facet.limit=25&hl=true&hl.simple.pre=%3Cem%20class=%22hilite%22%3E&fq=document_category:%22annotation%22&fq=regulates_closure:%22GO:0021538%22&facet.field=aspect&facet.field=taxon_subset_closure_label&facet.field=evidence_subset_closure_label&facet.field=regulates_closure_label&facet.field=annotation_class_label&facet.field=qualifier&facet.field=annotation_extension_class_closure_label&facet.field=assigned_by&facet.field=panther_family_label&q=*:*&packet=1&callback_type=search&json.wrf=jQuery21405841790202138231_1521762095709&_=1521762095710

![screen shot 2018-03-22 at 4 47 43 pm](https://user-images.githubusercontent.com/751274/37804293-d2928bac-2df0-11e8-88ae-827b769ebc17.png)

FYI @kltm  / @cmungall  / @deepakunni3 

Per our discussion today about adding the reference field.

**Comment by deepakunni3** [comment]
fixed via https://github.com/biolink/ontobio/pull/161 and https://github.com/biolink/ontobio/pull/162
