### ISSUE TITLE
create API method to return propagated parents terms for a given term

### ISSUE THREAD

**Issue by realmarcin** [monarch-initiative/biolink-api#172]
Something along these lines is done within the pair entity similarity method:

https://api.monarchinitiative.org/api/#!/pair%2Fsim/get_pair_sim_jaccard_resource

however there is no standalone call in biolink API.

**Comment by kshefchek** [comment]
scigraph neighbors is always an option, eg https://scigraph-ontology.monarchinitiative.org/scigraph/graph/neighbors?id=HP%3A0000460&depth=50&blankNodes=false&relationshipType=subClassOf&direction=OUTGOING&entail=false

edit: remember now equivalence is an issue
