### ISSUE TITLE
Add /function/{id}/gene

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/biolink-api#176]
Given a GO term, return related genes

Requested by @cbizon

**Comment by deepakunni3** [comment]
@kshefchek The `/bioentity/goterm/<id>/genes/` call takes a GO term as input and returns genes associated with that term. The call also requires a `relationship_type` argument which can have one of three values:
- `involved_in`
- `involved_in_regulation_of`
- `acts_upstream_of_or_within`

Wouldn't this call satisfy the above requirement? 

@cmungall Let me know if I missed something

**Comment by cbizon** [comment]
This does look good!   I think I had seen this at some point in the past, but never got it to work because I did not realize that relationship_type was required.

**Comment by deepakunni3** [comment]
@cbizon Great!

Yes, the `relationship_type` argument was a recent addition to that call.
