### ISSUE TITLE
/subgraph/<ontology>/<node> call gives error (due to url length?)

### ISSUE THREAD

**Issue by realmarcin** [monarch-initiative/biolink-api#179]
There are three different cases here.

One case is from within jupyter notebook using url request:

HTTPError: HTTP Error 400: Bad Request

Second is from browser - this worked with no error.

Third is from a python script using url request:
urllib.error.HTTPError: HTTP Error 400: Bad Request

Given that the pure browser case works there may be some limitations on the urllib library?

An example 'bad' url is here:
https://api-dev.monarchinitiative.org/api/ontol/subgraph/hp/HP%3A0002829?&cnode=HP%3A0003477&cnode=HP%3A0000099&cnode=HP%3A0002018&cnode=HP%3A0002586&cnode=HP%3A0002788&cnode=HP%3A0003470&cnode=HP%3A0006528&cnode=HP%3A0002721&cnode=HP%3A0001284&cnode=HP%3A0002013&cnode=HP%3A0100598&cnode=HP%3A0000238&cnode=HP%3A0002613&cnode=HP%3A0000554&cnode=HP%3A0003453&cnode=HP%3A0002014&cnode=HP%3A0000979&cnode=HP%3A0005681&cnode=HP%3A0006846&cnode=HP%3A0001937&cnode=HP%3A0001875&cnode=HP%3A0000709&cnode=HP%3A0001658&cnode=HP%3A0005558&cnode=HP%3A0004418&cnode=HP%3A0100778&cnode=HP%3A0001735&cnode=HP%3A0001394&cnode=HP%3A0000964&cnode=HP%3A0002204&cnode=HP%3A0003447&cnode=HP%3A0000999&cnode=HP%3A0002383&cnode=HP%3A0000365&cnode=HP%3A0002105&cnode=HP%3A0002076&cnode=HP%3A0005059&cnode=HP%3A0000751&cnode=HP%3A0001973&cnode=HP%3A0004944&cnode=HP%3A0100769&cnode=HP%3A0001269&cnode=HP%3A0002102&cnode=HP%3A0200029&cnode=HP%3A0100584&cnode=HP%3A0007141&cnode=HP%3A0001635&cnode=HP%3A0011944&cnode=HP%3A0002907&cnode=HP%3A0001289&cnode=HP%3A0001882&cnode=HP%3A0003401&cnode=HP%3A0000763&cnode=HP%3A0001878&cnode=HP%3A0000573&cnode=HP%3A0001824&cnode=HP%3A0002093&cnode=HP%3A0001025&cnode=HP%3A0001888&cnode=HP%3A0005318&cnode=HP%3A0001114&cnode=HP%3A0002960&cnode=HP%3A0100324&cnode=HP%3A0002171&cnode=HP%3A0000965&cnode=HP%3A0006530&cnode=HP%3A0002719&cnode=HP%3A0011947&cnode=HP%3A0011946&cnode=HP%3A0002206&cnode=HP%3A0001369&cnode=HP%3A0002099&cnode=HP%3A0001085&cnode=HP%3A0011034&cnode=HP%3A0100614&cnode=HP%3A0012211&cnode=HP%3A0100699&cnode=HP%3A0000819&cnode=HP%3A0000083&cnode=HP%3A0001945&cnode=HP%3A0002617&cnode=HP%3A0006532&cnode=HP%3A0003493&cnode=HP%3A0011096&cnode=HP%3A0000112&cnode=HP%3A0004950&cnode=HP%3A0000789&cnode=HP%3A0003765&cnode=HP%3A0010783&cnode=HP%3A0001370&cnode=HP%3A0000822&cnode=HP%3A0002863&cnode=HP%3A0002090&cnode=HP%3A0005547&cnode=HP%3A0002922&cnode=HP%3A0003365&cnode=HP%3A0007354&cnode=HP%3A0001909&cnode=HP%3A0011857&cnode=HP%3A0001890&cnode=HP%3A0001482&cnode=HP%3A0002097&cnode=HP%3A0003040&cnode=HP%3A0002098&cnode=HP%3A0000790&cnode=HP%3A0009830&cnode=HP%3A0007902&cnode=HP%3A0012622&cnode=HP%3A0100256&cnode=HP%3A0000613&cnode=HP%3A0001919&cnode=HP%3A0000793&cnode=HP%3A0001287&cnode=HP%3A0000762&cnode=HP%3A0003774&cnode=HP%3A0200042&cnode=HP%3A0001324&cnode=HP%3A0002716&cnode=HP%3A0000093&cnode=HP%3A0003326&cnode=HP%3A0002725&cnode=HP%3A0002665&cnode=HP%3A0001000&cnode=HP%3A0002092&cnode=HP%3A0004844&cnode=HP%3A0007359&cnode=HP%3A0004943&cnode=HP%3A0010702&cnode=HP%3A0000969&cnode=HP%3A0000718&cnode=HP%3A0100758&cnode=HP%3A0002923&cnode=HP%3A0001513&cnode=HP%3A0000872&cnode=HP%3A0001903&cnode=HP%3A0000123&cnode=HP%3A0006562&cnode=HP%3A0001907&cnode=HP%3A0100280&cnode=HP%3A0001297&cnode=HP%3A0008653&cnode=HP%3A0002331&cnode=HP%3A0002459&cnode=HP%3A0002621&cnode=HP%3A0002138&cnode=HP%3A0000155&cnode=HP%3A0003202&cnode=HP%3A0009831&cnode=HP%3A0002037&cnode=HP%3A0002633&cnode=HP%3A0002094&cnode=HP%3A0100749&cnode=HP%3A0000967&cnode=HP%3A0003565&cnode=HP%3A0002113&cnode=HP%3A0001873&cnode=HP%3A0003249&cnode=HP%3A0100665&cnode=HP%3A0001342&cnode=HP%3A0002448&cnode=HP%3A0001701&cnode=HP%3A0003124&cnode=HP%3A0002027&cnode=HP%3A0100806&cnode=HP%3A0000794&cnode=HP%3A0001271&cnode=HP%3A0002574&cnode=HP%3A0010871&cnode=HP%3A0002516&cnode=HP%3A0003651&cnode=HP%3A0006510&cnode=HP%3A0100532&cnode=HP%3A0003259&cnode=HP%3A0003881&cnode=HP%3A0002527&cnode=HP%3A0100279&cnode=HP%3A0100647&cnode=HP%3A0001974&cnode=HP%3A0000752&cnode=HP%3A0000855&cnode=HP%3A0002063&cnode=HP%3A0000100&cnode=HP%3A0100724&cnode=HP%3A0000988&cnode=HP%3A0006515&cnode=HP%3A0002196&cnode=HP%3A0011945&cnode=HP%3A0006775&cnode=HP%3A0005523&cnode=HP%3A0000246&cnode=HP%3A0001250&cnode=HP%3A0002239&cnode=HP%3A0001970&cnode=HP%3A0000491&cnode=HP%3A0001880&cnode=HP%3A0002202&cnode=HP%3A0000978&cnode=HP%3A0100533&cnode=HP%3A0011953&cnode=HP%3A0100608&cnode=HP%3A0011972&cnode=HP%3A0006536&cnode=HP%3A0003613&cnode=HP%3A0004420&cnode=HP%3A0100827&cnode=HP%3A0000836&cnode=HP%3A0005310&cnode=HP%3A0005305&cnode=HP%3A0002955&cnode=HP%3A0002625&include_ancestors=true&include_meta=false&include_descendants=false&relation=subClassOf

**Comment by deepakunni3** [comment]
The limitation here is brought by gunicorn, where the max URL length is `4094`.
The URL length restriction can be changed to allow for longer URLs, but wouldn't it make more sense to fire a POST request instead of a GET?

Or should we provide both a GET and a POST method for the same route?

**Comment by kltm** [comment]
GETs are easier to play with, POSTs work better in real life. Where possible, I try and provide both with the same functionality (although HTTP/REST purists would likely disagree).
