### ISSUE TITLE
disease/phenotypes route failing

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/biolink-api#186]
E.g. 

`curl -X GET "https://api.monarchinitiative.org/api/bioentity/disease/DOID%3A9352/phenotypes/?rows=100&exclude_automatic_assertions=false&fetch_objects=true&use_compact_associations=false" -H "accept: application/json”`

**Comment by deepakunni3** [comment]
While trying this query with a local instance of biolink-api yields the following error:
```
File "/Users/deepak.unni3/GIT/biolink-api/working-environment/lib/python3.6/site-packages/ontobio/golr/golr_query.py", line 1270, in exec
  ff = oq_results.facets['facet_fields']
KeyError: 'facet_fields'
```

It looks like when `fetch_objects=true`, GolrAssociationQuery fires a second Golr query.
Somehow the results from this query does not have `facets` or `oq_results.facets` is empty.

@kshefchek Any idea what might be causing this?

Following are the params sent in the second Golr query:
```
{'q': '*:*', 'fq': ['subject_category:"disease"', 'object_category:"phenotype"', 'subject_closure:"DOID:9352"', '-evidence_object_closure:"ECO:0000501"'], 'facet': 'off', 'facet.field': ['object'], 'facet.limit': -1, 'facet.mincount': 1, 'fl': [], 'rows': 0}
```

**Comment by deepakunni3** [comment]
Majority of the calls are now failing at that exact same spot in `GolrAssociationQuery`.

**Comment by deepakunni3** [comment]
After discussing with @kshefchek , it looks like a change in one of the dependencies, Flask-RESTPlus from `v1.10.1` to `v1.11`, seemed to exacerbate a previously existing upstream bug.

In https://github.com/biolink/biolink-api/blob/master/biolink/api/bio/endpoints/bioentity.py#L26

`type=bool` is always interpreted as `True`. 

Flask RESTPlus provides types for handling such boolean parameters: `type=inputs.boolean`.
