### ISSUE TITLE
biolink api doesn't provide an anchor link anymore

### ISSUE THREAD

**Issue by nathandunn** [monarch-initiative/biolink-api#194]
From here:   https://api.monarchinitiative.org/api/

In the olden days I used to be to click and the API would change:

https://api.monarchinitiative.org/api/#apiCallIjustClickedOn

Would be great.  I think you just have to reconfigure it so ```deepLinking=true```

https://github.com/swagger-api/swagger-ui/issues/2884

**Comment by nathandunn** [comment]
pinging @deepakunni3  / @kshefchek / @cmungall 

Maybe the next time the biolink server is updated this could be switched on?    Looks like its just a simple configuration.  

I use biolink for a lot of references, so this would be very handy to have again.

**Comment by deepakunni3** [comment]
@nathandunn Will look into this soon.

This happened as a result of updating one of the biolink-api dependencies, Flask-RESTPlus, which generates the Swagger JSON and UI.

**Comment by deepakunni3** [comment]
@nathandunn Digging around a bit, and looking at the linked issue, you can enable anchor links as follows:

https://api.monarchinitiative.org/api?deepLinking=true#apiCallIjustClickedOn

Ex: 
http://api.monarchinitiative.org/api?deepLinking=true#/bioentity/get_disease_pathway_associations

An extra bit of step. Ideally deepLinking should be `true` by default in Swagger-UI but thats not the case.

**Comment by nathandunn** [comment]
That works for me: 

https://api.monarchinitiative.org/api/?deepLinking=true#/bioentity/get_gene_expression_associations
