### ISSUE TITLE
bioentityset/slimmer/function should provide a relationship_type argument to determine which closure to use

### ISSUE THREAD

**Issue by deepakunni3** [monarch-initiative/biolink-api#201]
Currently the GOlr query made by `bioentityset/slimmer/function` call is different in comparison to its analogous AmiGO query.

`bioentityset/slimmer/function` call is operating over `isa_partof_closure` instead of  `regulates_closure`.

The solution would be to provide a `relationship_type` argument for this call, similar to the `bioentity/goterm/{id}/genes/` call, where the `relationship_type` will determine which closure to use in the GOlr query:
- involved_in -> `isa_partof_closure`
- acts_upstream_of_or_within -> `regulates_closure`

@kltm @cmungall @selewis @nathandunn

**Comment by deepakunni3** [comment]
Adding comments from https://github.com/biolink/ontobio/pull/212,

> In future iterations of our golr schema, we should simply name the closure fields for entity and association docs according to the gp2term relationship. 
>
> In other words, isa_partof_closure would be for GO ontology docs (since is_a and part_of are relations that hold e.g. between two processes), and involved_in and causally_upstream_of_or_within would be in assoc docs (since this holds between gp and a term) 
>
> This would obviate the need for a confusing mapping, where we say "for involved in use the isapartof closure" etc

**Comment by nathandunn** [comment]
@deepakunni3   Has this made its way into production?

**Comment by nathandunn** [comment]
https://agr-jira.atlassian.net/browse/AGR-1108

**Comment by deepakunni3** [comment]
@nathandunn The production BioLink API is still due an update.

**Comment by deepakunni3** [comment]
@nathandunn The changes should be live now.
