### ISSUE TITLE
ribbon / slimmer function: add gene symbol for display in with column

### ISSUE THREAD

**Issue by nathandunn** [monarch-initiative/biolink-api#208]
https://github.com/geneontology/ribbon/issues/46

**Comment by deepakunni3** [comment]
Would it be possible to add more details from the JIRA ticket?

**Comment by nathandunn** [comment]
I think that's it ;) . 

Basically everything in the `with` or `Based on` table, but especially genes should be translated to the appropriate symbol.  From here: https://www.alliancegenome.org/gene/RGD:620615

<img width="925" alt="screen shot 2018-08-27 at 10 55 47 pm" src="https://user-images.githubusercontent.com/751274/44699995-6562a480-aa4c-11e8-95e8-9b5544b2caff.png">

**Comment by nathandunn** [comment]
If the symbol is available, could just be provided an another field (and name if it is there, though I can't imagine it would be used).

**Comment by selewis** [comment]
This is the same as #209 (it's NOT allele IDs). Here's the answer:

Basically it's about what is being returned in the response. Right now in the JSON field being returned labeled "evidence_with" there is just a simple list of ids. It would be be preferred if each entry in this "evidence_with" list looked similar to the "subject" entry and included - label, id, and taxon - for each entry.

**Comment by selewis** [comment]
Same as #209 so closing
