### ISSUE TITLE
HGNC ids not being looked up properly

### ISSUE THREAD

**Issue by nathandunn** [monarch-initiative/biolink-api#226]
The is affecting all of the ribbon code using human data. 

No work with hgnc id: HGNC:11204

https://api.monarchinitiative.org/api/bioentityset/slimmer/function?&slim=GO:0003824&slim=GO:0004872&slim=GO:0005102&slim=GO:0005215&slim=GO:0005198&slim=GO:0008092&slim=GO:0003677&slim=GO:0003723&slim=GO:0001071&slim=GO:0036094&slim=GO:0046872&slim=GO:0030246&slim=GO:0003674&slim=GO:0008283&slim=GO:0071840&slim=GO:0051179&slim=GO:0032502&slim=GO:0000003&slim=GO:0002376&slim=GO:0050877&slim=GO:0050896&slim=GO:0023052&slim=GO:0010467&slim=GO:0019538&slim=GO:0006259&slim=GO:0044281&slim=GO:0050789&slim=GO:0042592&slim=GO:0007610&slim=GO:0008150&slim=GO:0005576&slim=GO:0005737&slim=GO:0005856&slim=GO:0005739&slim=GO:0005634&slim=GO:0005694&slim=GO:0016020&slim=GO:0031982&slim=GO:0071944&slim=GO:0030054&slim=GO:0042995&slim=GO:0032991&slim=GO:0045202&slim=GO:0005575&subject=HGNC:11204

Works with UniprotKB ID mapped to the same gene:

https://api.monarchinitiative.org/api/bioentityset/slimmer/function?&slim=GO:0003824&slim=GO:0004872&slim=GO:0005102&slim=GO:0005215&slim=GO:0005198&slim=GO:0008092&slim=GO:0003677&slim=GO:0003723&slim=GO:0001071&slim=GO:0036094&slim=GO:0046872&slim=GO:0030246&slim=GO:0003674&slim=GO:0008283&slim=GO:0071840&slim=GO:0051179&slim=GO:0032502&slim=GO:0000003&slim=GO:0002376&slim=GO:0050877&slim=GO:0050896&slim=GO:0023052&slim=GO:0010467&slim=GO:0019538&slim=GO:0006259&slim=GO:0044281&slim=GO:0050789&slim=GO:0042592&slim=GO:0007610&slim=GO:0008150&slim=GO:0005576&slim=GO:0005737&slim=GO:0005856&slim=GO:0005739&slim=GO:0005634&slim=GO:0005694&slim=GO:0016020&slim=GO:0031982&slim=GO:0071944&slim=GO:0030054&slim=GO:0042995&slim=GO:0032991&slim=GO:0045202&slim=GO:0005575&subject=UniProtKB:H9GEA7

**Comment by deepakunni3** [comment]
@nathandunn Looks like the lookup from HGNC to UniProtKB yields no result. This is unusual since this was working before.

Will keep looking...

**Comment by deepakunni3** [comment]
@nathandunn This bug was a result of the slimmer referring to `https://scigraph-data-dev.monarchinitiative.org/scigraph/`, which I am assuming was taken down recently as a result of migration of Monarch servers. 

That URL was temporary to begin with and we should have been using `https://scigraph-data.monarchinitiative.org/scigraph/` as defined in `config.yaml`.

**Comment by nathandunn** [comment]
@deepakunni3  Great.  Should I bug @kshefchek  to update the API server?

**Comment by deepakunni3** [comment]
Yes, @kshefchek would be able to help with updating the production server.
Although, I still am not able to get the desired behavior from the api-dev. But it works properly on a local instance.

**Comment by nathandunn** [comment]
Ah okay.    Weird.

**Comment by deepakunni3** [comment]
Oh wait. nevermind. The build is running.

If I have a success on api-dev then I can trigger an update myself for the prod API.

**Comment by nathandunn** [comment]
Its working here and on production.  Thanks @deepakunni3  !

**Comment by deepakunni3** [comment]
Thanks to @kshefchek 

This was happening because we had an exception being thrown server side (related to Ontobio). 
Kent had a workaround for it which fixed the issue on `master` but its still an issue on `dev`. But the fix is temporary and will need to be removed when we release next version of Ontobio.
