### ISSUE TITLE
Allow configuration of endpoints in a biolink installation

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/biolink-api#235]
The reference installation includes the union of all possible endpoints.

We want to make an API endpoint for GO, but only expose endpoints of relevance for GO

@deepakunni3 worked on configurability for AGR such that some route groupings in app.py could be masked. However, some modules like bioentity.py contain multiple endpoints, some of which should be filtered. We could split bioentity into multiple file/modules but that may get unwieldy.

I think the way to go might be dynamic routing driven by configuration

cc @lpalbou

**Comment by deepakunni3** [comment]
Fixed via https://github.com/biolink/biolink-api/pull/237
