### ISSUE TITLE
ClinVarVariant:549356 returns 404

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/biolink-api#258]
https://api-dev.monarchinitiative.org/api/bioentity/variant/ClinVarVariant:549356?fetch_objects=true&unselect_evidence=false&exclude_automatic_assertions=false&use_compact_associations=false&get_association_counts=true&rows=100

Returns a 404 and msg:
"SciGraph dynamic/cliqueLeader yields no result for ClinVarVariant:549356"

However, this call should work:
https://scigraph-data-dev.monarchinitiative.org/scigraph/dynamic/cliqueLeader/ClinVarVariant%3A549356.json

confirmed scigraph-data-dev is configured in 
/opt/biolink-api/conf
and
/opt/biolink-api/venv/lib/python3.6/site-packages/ontobio/config.yaml

btw, the new error messages are great - thanks @deepakunni3!

reported by @DoctorBud

**Comment by deepakunni3** [comment]
@kshefchek Glad to hear that! 

I'll take a look and see whats going on 👍

**Comment by deepakunni3** [comment]
Okay, so it looks like the SciGraph URL always defaults to scigraph-data even if the config has scigraph-data-dev.

**Comment by deepakunni3** [comment]
@kshefchek Do you recommend having the dev and prod configurations in the same `config.yaml` and have the app state determine which configuration to use?

**Comment by kshefchek** [comment]
I think the way it works now is fine.  If we wanted to change it up we could have two config files and have an argument or environment variable determine which config to use.
