### ISSUE TITLE
OSError: Exec format error with Werkzeug 0.15

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/biolink-api#260]
When starting up biolink in development mode via:

    python biolink/app.py

I get the exception OSError: [Errno 8] Exec format error.  I'm on Ubuntu 16.04, have tried with python 3.5, 3.6, 3.7.  Werkzeug 0.14 works fine.

**Comment by deepakunni3** [comment]
@kshefchek See related discussion here: https://github.com/pallets/werkzeug/issues/1482

Looks like the easiest way to get around this would be to add a shebang line to `app.py`:
```python
#!/usr/bin/env python
```

**Comment by anishpal29** [comment]
Hi same issue here. Tested on
Centos 7.4 with python 3.6 after building docker image.
it is working on local machine on windows 10.
