### ISSUE TITLE
Improve /api/graph/edges/from/ endpoint

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/biolink-api#273]
Currently the graph edges endpoint hardcodes the depth and direction of edges to traverse:
https://github.com/biolink/biolink-api/blob/3219fef/scigraph/scigraph_util.py#L131

Ideally the endpoint would be as flexible as the scigraph /graph/neighbors/ function:
https://scigraph-data.monarchinitiative.org/scigraph/docs/

**Comment by deepakunni3** [comment]
Fixed via https://github.com/biolink/biolink-api/pull/281
