### ISSUE TITLE
Add all monarch association types as biolink routes

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/biolink-api#278]
With the association types and routes.yaml we should be able to determine what routes have yet to be added to biolink from the monarch solr:

https://solr.monarchinitiative.org/solr/golr/select/?facet.field=association_type&q=*%3A*&facet=true&facet.method=enum&facet.limit=3000&rows=0&wt=json&facet.mincount=1&indent=on&facet.sort=count

For exmaple: variant/:id/models, and all case endpoints that would be needed to create our UDP pages, eg: http://monarchinitiative.org/case/:MONARCH:c000017

Note that gene_temporal is bad naming and should be merged with gene interactions (colocalization data)

**Comment by deepakunni3** [comment]
@kshefchek I think I was being conservative when adding routes to avoid routes that never returned any associations (and I must have missed a few in the process). 

But I saw @DoctorBud mention that certain pages fail to load because it expects routes to be symmetrical.

Do you recommend adding all possible enumeration of routes to the API and then have the API respond with an empty JSON if that route is not yet implemented?

**Comment by kshefchek** [comment]
> Do you recommend adding all possible enumeration of routes to the API and then have the API respond with an empty JSON if that route is not yet implemented?

I don't think we should add routes if we know it will not return any data (in the current db).  But I may be misunderstanding.  I know there are some nuances with sequence features being treated as models.

**Comment by deepakunni3** [comment]
Okay, just making sure. Couple of months back I had pruned many of the routes that never returned any associations.

**Comment by deepakunni3** [comment]
After doing the comparison between `routes.yaml` and facets for `association_type`, it looks like the following routes are missing:
- `variant/<id>/models`
- `model/<id>/cases`
- `case/<id>/models`
- `case/<id>/diseases`
- `disease/<id>/cases`
- `case/<id>/variants`
- `variant/<id>/cases`
- `case/<id>/genotypes`
- `genotype/<id>/cases`
- `case/<id>/genes`
- `gene/<id>/cases`
- `case/<id>/phenotypes`
- `phenotype/<id>/cases`

@kshefchek Do you want me to take a stab at adding these routes or have you started working on this already?

**Comment by kshefchek** [comment]
go for it!
