### ISSUE TITLE
500 for homologs endpoint

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/biolink-api#287]
Our uptime URL is currently returning a 500:
https://api.monarchinitiative.org/api/bioentity/gene/NCBIGene:3630/homologs/?homology_type=O&fetch_objects=false

An exception occurred: search_associations() got multiple values for keyword argument 'relation'

We are running on commit f1c00ed7, I can revert to an earlier version for now.

**Comment by deepakunni3** [comment]
@kshefchek Thanks for reverting to an earlier commit.

I think my recent relation filter PR is messing up with a few GO specific routes.
I'll have a fix for this soon.

**Comment by deepakunni3** [comment]
@kshefchek This should be closed now, right?
