### ISSUE TITLE
Minor improvements for term pages on monarch-ui

### ISSUE THREAD

**Issue by monicacecilia** [monarch-initiative/biolink-api#308]
Dear @deepakunni3 - I am bringing [this ticket](https://github.com/monarch-initiative/monarch-ui/issues/96) over from the monarch-ui repo. I don't have superpowers to assign you here, so I am hereby assigning you. :bowtie: 

------------

#### On Performance: 
- [x] From @cmungall: Some term pages can be slow to load. It would be good to diagnose so we can come up with a plan, e.g., http://beta.monarchinitiative.org/phenotype/HP:0010831. This may have been a temporary issue, but it would be good to get an idea of load time of different pages under different loads.

- From @jmcmurry:  In latest PR by @iimpulse responsiveness seems to be better in my hands. Still could improve, but thought I would mention.

------------

#### On Counts: 

- [x] From @cmungall: We calculate both ```|association|``` and ```|gene|```, but we show these counts in different places (the former once you click on the tab, the latter on the tab itself) which can look a bit odd. See for example http://beta.monarchinitiative.org/phenotype/HP:0010831#gene and notice '1624 Genes' and '2724 gene associations' (screenshot below).

- [x] From @kshefchek:  I think it makes sense to get rid of distinct counts in favor of globally using association counts. The exception being special stats endpoints where we only want unique counts of entities of type <T>. 
   - I think both of these issues (performance, counts) come from upstream components - solr, ontobio, biolink. 
   - See also this long standing ticket from monarch-app: https://github.com/monarch-initiative/monarch-app/issues/1263

<img width="506" alt="Screen Shot 2019-07-31 at 4 15 53 PM" src="https://user-images.githubusercontent.com/1714621/62254565-81826a80-b3ae-11e9-81b0-6b79e975c15f.png">

**Comment by monicacecilia** [comment]
Added this ticket to [Monarch's New UI v1.0 Project Board](https://github.com/orgs/monarch-initiative/projects/8).

**Comment by deepakunni3** [comment]
After reviewing the details of this issue (Thanks @monicacecilia for assembling all this info), following are the action items:
- avoid distinct counts for `get_association_counts`; show raw association counts instead, to avoid confusion.
- add an additional parameter to the route for distinct association counts; for example `get_distinct_association_counts` such that we can get distinct counts when needed

@kshefchek Do you recommend this approach or an entirely new route for getting distinct association counts?

**Comment by monicacecilia** [comment]
@kshefchek - ping! :bowtie:

**Comment by kshefchek** [comment]
I think this can be closed with https://github.com/biolink/biolink-api/pull/310

**Comment by kshefchek** [comment]
closed with #310
