### ISSUE TITLE
Add category to autocomplete query

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/biolink-api#325]
I would like to restrict autocomplete to gene, allele, phenotype, etc

E.g
https://api.monarchinitiative.org/api/search/entity/autocomplete/Bloc1s6&category=allele

**Comment by deepakunni3** [comment]
We do this already.

For example:
https://api.monarchinitiative.org/api/search/entity/autocomplete/Bloc1s6?&category=gene

gives only results for type `gene`

**Comment by cmungall** [comment]
doh forgot the '?'. And somehow I didn't spot the category field when I looked at the swagger
