### ISSUE TITLE
Switch scigraph annotate backend to scigraph-ontology

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/biolink-api#355]
Currently the backend is wired to scigraph-data but I think the ontology graph works better for nlp.

Long term we should look to replace this entirely, as @deepakunni3 I know you've been testing out some pure python nlp approaches. In some cases our solr endpoint performs better than the scigraph nlp:
Scigraph nlp: "diabetes type II" -> MONDO:0005015  diabetes mellitus (disease)
Solr: "diabetes type II" -> HP:0005978  Type II diabetes mellitus

**Comment by cmungall** [comment]
As I recall there are some entities in the data graph not in the ontology graph. e.g I believe we load human genes in the ontology graph but not other genes? This may not be a concern but it should be well documented do there is no unexpected behavior.

Curious to see your solr experiments
