### ISSUE TITLE
licensing vs usage of api.monarchinitiative.org/api

### ISSUE THREAD

**Issue by olszewskip** [monarch-initiative/biolink-api#360]
Can one legally programatically use api.monarchinitiative.org/api in a commercial software without paying?
Which license am I touching sending requests to api.monarchinitiative.org/api?

**Comment by kshefchek** [comment]
the license for this repo is here - https://github.com/biolink/biolink-api/blob/master/LICENSE which looks permissive for commercial use

**Comment by olszewskip** [comment]
Thank You @kshefchek for the fast response.
But I'm not actually immediately interested in using the source code of this repository, so much as simply calling the api mentioned in README's "Demo" section. If I understand correctly, through the api, I'm directly or indirectly accessing many databases (listed here: https://monarchinitiative.org/about/data-sources) integrated by the effort of the Monarch Initiative, some of which are copyright- or copyleft-protected. Hence my worries, how should I (or could I) license my software which sends requests to https://api.monarchinitiative.org/api?

**Comment by kltm** [comment]
@olszewskip 
The straightforward answer is, unfortunately, not particularly straightforward: you will have to determine what you can use on your own for the uses that you have in mind--there is no blanket declaration that can be made. A short overview and explanation can be found in the "Data" section of the Licensing page (https://monarchinitiative.org/about/licensing). Data reusability is a huge problem; a good overview can be found at the Reusable Data Project (http://reusabledata.org), along with reusability scores for Monarch and the data upstreams.

**Comment by olszewskip** [comment]
Thank You @kltm.
But then doesn't it mean that effectively all those licenses are in force for each and every api request? How can one guarantee that only a specified selection of databases is used in resolving any given query to https://api.monarchinitiative.org/api. E.g., if I understand correctly, even if my query explicitly mentions only curie identifiers from free datasources, the processing of my request and the returned response may involve any other datasource that was used by the Initiative?

**Comment by kltm** [comment]
@olszewskip 
As far as the data you access from the API, that would be a reasonable conclusion: you will have to determine what you can use on your own for the uses that you have in mind. At this point in time, the data from the API is not separately marked with licensing information, so there is currently no structured way to guarantee your use and reuse profile for the data received from any given call.

**Comment by kshefchek** [comment]
closing this ticket although we should document these issues somewhere - perhaps as a link on the swagger UI
