### ISSUE TITLE
api/sim/search: 504 Gateway Time-out

### ISSUE THREAD

**Issue by dominickdm** [monarch-initiative/biolink-api#370]
Hello,

Since several days now, we get a HTTP 504 error when using the api/sim/search API call. What is the reason and can it be fixed?  

https://api.monarchinitiative.org/api/sim/search?is_feature_set=true&metric=phenodigm&id=HP%3A0001166&id=&limit=10

![image](https://user-images.githubusercontent.com/40289256/110308128-06f4e480-8000-11eb-91d8-97716ced8a18.png)

**Comment by kshefchek** [comment]
Hi @dominickdm, the server hosting this service was maxed out, and for some reason our uptime monitoring did not pick up on this.  I've moved the service over to another server and it's back up.  Apologies for the downtime.

**Comment by dominickdm** [comment]
Hi @kshefchek, 
Thank you for looking into it and fixing it, i can confirm that it works again for us!

**Comment by kshefchek** [comment]
Great!  Please let us know if theres anything we can do to improve the service
