### ISSUE TITLE
Add autocomplete function to help POET

### ISSUE THREAD

**Issue by monicacecilia** [monarch-initiative/biolink-api#372]
To moving forward with POET and its ability to access Mondo/OMIM information, add autocomplete on 
- [ ] free text 
- [ ] OMIM ids (see #368)
- [ ] Mondo ids 

And have the API return:
- [ ] Exact matches MONDO==OMIM
- [ ] Superclasses MONCO ={OMIM1, OMIM2, ...}

@pnrobinson added that both of these need additional bits of information such as _de-shoutified_ name.

@iimpulse, @kshefchek, @cmungall

**Comment by pnrobinson** [comment]
@kshefchek @cmungall -- could you let us know if this is going to be possible? Do you need us to do a PR? This is the major blocker right now so if this is impossible please let us know asap so we can find something else

**Comment by kshefchek** [comment]
I think this can be closed via https://github.com/biolink/biolink-api/pull/373? @pnrobinson please reopen if anything else is needed for POET
