### ISSUE TITLE
/sim/search - limit question 

### ISSUE THREAD

**Issue by dominickdm** [monarch-initiative/biolink-api#374]
Hi,

We have a question regarding the sim/search API.

Why is the first match not the same if we do exactly the same call, but with a different limit? We would expect that the first match is always the same and that the limit is just a way to limit the list..

One of our examples (we have the same with other metrics too..)
Example:

Jaccard - Limit 1 
https://api.monarchinitiative.org/api/sim/search?metric=jaccard&id=HP%3A0000954&id=HP%3A0000286&id=HP%3A0001388&id=HP%3A0002511&limit=1&taxon=9606

![image](https://user-images.githubusercontent.com/40289256/118825466-ff34a480-b8ba-11eb-89cc-efb2a86e58b3.png)

Jaccard - Limit 10
https://api.monarchinitiative.org/api/sim/search?metric=jaccard&id=HP%3A0000954&id=HP%3A0000286&id=HP%3A0001388&id=HP%3A0002511&limit=10&taxon=9606

![image](https://user-images.githubusercontent.com/40289256/118825589-170c2880-b8bb-11eb-977e-937c1e2116ba.png)

**Comment by kshefchek** [comment]
this is fixed now @dominickdm, please let us know if you run into any more bugs
