### ISSUE TITLE
504 errors for /sim/search when limit varies

### ISSUE THREAD

**Issue by cemordaunt** [monarch-initiative/biolink-api#379]
Thanks so much for maintaining this API. I've been running queries with /sim/search and I keep getting 504 Gateway Timeouts when I change the limit setting. I also occasionally get 500 errors. See below for examples, I'd really appreciate any help to solve this.

**Query 1 (limit = 10)**
https://api.monarchinitiative.org/api/sim/search?is_feature_set=false&metric=phenodigm&id=MONDO%3A0001134&limit=10&taxon=10090

<img width="1792" alt="Query 1" src="https://user-images.githubusercontent.com/13224059/131739059-5768f545-1f02-4db0-bedc-3435edb0ce31.png">

**Query 2 (limit = 5)**
https://api.monarchinitiative.org/api/sim/search?is_feature_set=false&metric=phenodigm&id=MONDO%3A0001134&limit=5&taxon=10090

<img width="1051" alt="Query 2" src="https://user-images.githubusercontent.com/13224059/131739075-f1da5e3f-8029-4d4c-b083-c393d25181ea.png">

**Comment by kshefchek** [comment]
thanks for reaching out! the underlying [analysis server](https://status.monarchinitiative.org/784445233) that drives this service went down for ~24 hours, and I think what you were seeing is related to some odd caching behavior.  The lower limit query should now be working.  In the future we may add a rate limit to make sure the service can stay up - would you mind sharing your analysis needs (ie total number of requests, frequency)?

**Comment by kshefchek** [comment]
we've recently updated some limits that should result in better performance moving forward, please let us know if you continue to see issues.  Also feel free to reach out to discuss your analysis needs - https://monarchinitiative.org/help/contact

**Comment by cemordaunt** [comment]
Great, thank you for your help on this!
