### ISSUE TITLE
Question about the phenotyping sufficiency score

### ISSUE THREAD

**Issue by sophie22** [monarch-initiative/biolink-api#384]
Hello,

I'm doing a Masters project on the utility of phenotype information for variant prioritisation and came across the conference [paper](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwiDltTT85z0AhVM3qQKHbTZBLsQFnoECAkQAQ&url=https%3A%2F%2Fzenodo.org%2Frecord%2F834091%2Ffiles%2FPhenoDay_SufficiencyScore_camera_ready_final.pdf&usg=AOvVaw1qCijsz5xH9keSzD8EZ_z7) about quantifying the sufficiency of phenotype terms collected for a patient. The link for the API in the paper is no longer available but I found an endpoint in the BioLink API [/sim/score/](https://github.com/biolink/biolink-api/blob/master/biolink/api/sim/endpoints/annotation_score.py) which appears to be the one I'm after.

My question is the following: is this the correct endpoint to get the sufficiency score, and if so what is the meaning of/differences between the 3 scores returned: simple, scaled and categorical_score?

Thank you,
Sophie

**Comment by sierra-moxon** [comment]
Hi Sophie -

Is this the endpoint you are using (with example HP values in my example): https://api.monarchinitiative.org/api/sim/score?id=HP%3A0004935&absent_id=HP%3A0002828 

I believe that is the API endpoint you should be using, yep! 
In the paper you linked, the three score values are explained in section 2.5 and I'm afraid I'd make it more confusing if I tried to explain it differently here :).  Are there any more specific questions that I could attempt to find answers to?  

thanks for reaching out!

**Comment by sophie22** [comment]
Thank you very much, this is what I was looking for.
Best wishes,
Sophie
