### ISSUE TITLE
Allow configuration to point to other services

### ISSUE THREAD

**Issue by jnguyenx** [monarch-initiative/biolink-api#48]
The external URLs are hard-coded. It'll be useful to be able to have that configurable so biolink can point to other endpoints.

For Monarch we'll use that to point to the dev vs prod services.

**Comment by cmungall** [comment]
In theory this could be done by simply keeping site-specific configurations in the site-specific fork, but this is a bit unpleasant.

I assume we want something like a yaml file with all URLs configured in it
