### ISSUE TITLE
Add parameter to dynamically map ID spaces

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/biolink-api#5]
In the golr schema we always choose a clique leader from the equivalence set for setting fields like subject, object. In Monarch this is done by @jnguyenx's clique leader code. In GO this is hardwired along partly political grounds as to whose ID to show.

Clients often want associations mapped to their ID space of choice. While it is always possible to do this as a post-processing step using an ID map service, better to give the option to do this on the fly.

In Monarch we can do this because we have closures on subjects as well as objects. (this also gives us superclass closures which is unwanted, but in general these are ids in a different id space; longer term we should have one closure for equivalence, and one for reflexive closure over subclass).

@kltm - as part of general alignment can we have subject_closures in amigo-golr too? No action required on your part now I can make experimental PR, this is just for context.

**Comment by kltm** [comment]
Any kind of closure can be had, they just need to be added to the metadata and made sure that they come out in the right spot in the UI, etc.
Practically, the loader will need a lot of kicking on the GO side. Or a rewrite.

**Comment by cmungall** [comment]
rewrite!
