### ISSUE TITLE
search/entity/{term} doesn't return anything

### ISSUE THREAD

**Issue by lhannest** [monarch-initiative/biolink-api#58]
The examples are
https://api.monarchinitiative.org/api/search/entity/parkinson
https://api.monarchinitiative.org/api/search/entity/shh
https://api.monarchinitiative.org/api/search/entity/femur

For each the response is empty.

The swagger page also appears to be acting up for this query, which might be relevant.

**Comment by cmungall** [comment]
@kshefchek or@DoctorBud - can you look? May just need to up the version of ontobio used, this was only added latest release on pypi

**Comment by cmungall** [comment]
Reopening until its deployed on production - will do this with @kshefchek tomorrow
