### ISSUE TITLE
FB vs. FlyBase

### ISSUE THREAD

**Issue by selewis** [monarch-initiative/biolink-api#67]
For example: is it FlyBase:FBgn0005558 or FB:FBgn0005558?
There is a discordancy in Biolink, because the method to retrieve the orthologs for a gene uses 'FlyBase' for the matching ortholog identifiers, but if subsequently you try and use this ID to retrieve GO annotations nothing will come back because GOlr (and PANTHER and the GPCR) use FB as the resource prefix.

**Comment by cmungall** [comment]
Yes, it's a discrepancy between GO and Monarch (Biolink itself is neutral). 

I thought we already dealt with this:

https://github.com/biolink/ontobio/blob/68b1dc4d23c32f4279967129c11b9bee7c6ba025/ontobio/golr/golr_query.py#L121-L124

Maybe the monarch one is lacking behind in ontobio version

**Comment by cmungall** [comment]
@selewis can you confirm if this is fixed in the dev version?

**Comment by selewis** [comment]
Hacks in place to swap things in and out. Needs to be revisited later.
