### ISSUE TITLE
Gene-function operation does not work for HGNC IDs

### ISSUE THREAD

**Issue by selewis** [monarch-initiative/biolink-api#79]
A query (slimmer bio link query) using the HGNC:1110 id will retrieve the mouse ortholog information, but nothing for human. Conversely however, for the same gene UniProtKB:P38398, the query will return information for both human and mouse (as expected). In a sense it 'works' but not if data goes missing depending on what id is used. I have a feeling this is a general issue and will require testing with numerous permutations.

**Comment by cmungall** [comment]
Withdrawn: http://www.genenames.org/cgi-bin/gene_symbol_report?q=data/hgnc_data.php&hgnc_id=1110

However, still fails for valid IDs such as HGNC:6081

**Comment by cmungall** [comment]
This is the problem: https://github.com/SciGraph/SciGraph/issues/135

We can implement a workaround
